### ISSUE TITLE
Create a "Cancelled" membership type with no rights, not purchasable

### ISSUE THREAD

**Issue by offbyone** [ChicagoWorldcon/wellington#38]
This is so that reservations that are disabled can be tombstoned in the system.

**Comment by offbyone** [comment]
We can trivially create one, but it's gonna display like a real reservation. That might not be desirable. For now, though, we can get it in place, and it'll convey what we need until things get better. Leaving this open to track the display portions.

**Comment by kathybond** [comment]
The basic problem is that a member has 2 memberships. We want on our end to refund and disable one. Then, the member wants to log back-in to interact with their "active" membership. 

So, we want the member to only see one membership when they log-in basically. Or rather, see their active membership so that they don't end up trying to upgrade their inactive membership or use Hugo rights with their inactive membership.

**Comment by offbyone** [comment]
This was added some time ago.
